# Generated by Django 4.2.30 on 2026-05-25 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ehr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_summary', models.JSONField(blank=True, help_text="Aggregate summary of the patient's entire history", null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_extracted_text', models.TextField(blank=True, null=True)),
                ('ai_summary', models.JSONField(blank=True, help_text='Structured summary of the document', null=True)),
                ('identified_conditions', models.JSONField(blank=True, help_text='List of extracted conditions', null=True)),
                ('extracted_medications', models.JSONField(blank=True, help_text='List of extracted medications', null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='ehr.documentattachment')),
            ],
        ),
    ]
