# Generated by Django 4.2.30 on 2026-05-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprocessingmetrics',
            name='is_success',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='websocketconnectionmetrics',
            name='connected_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='aiprocessingmetrics',
            index=models.Index(fields=['start_time'], name='analytics_a_start_t_4fb819_idx'),
        ),
    ]
