# Generated by Django 4.2.30 on 2026-05-26 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ehr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTimelineSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_progression', models.JSONField(blank=True, default=list)),
                ('medication_history_analysis', models.JSONField(blank=True, default=dict)),
                ('recurring_conditions', models.JSONField(blank=True, default=list)),
                ('risk_trend_analysis', models.JSONField(blank=True, default=dict)),
                ('ai_generated_summary', models.TextField(blank=True, null=True)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('ehr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_summary', to='ehr.ehrrecord')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_summary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalInsightEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
