# Generated by Django 4.2.30 on 2026-05-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_department_name_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
