# Generated by Django 4.2.30 on 2026-05-25 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0011_alter_department_name_alter_doctor_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='EHRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('lab_report', 'Lab Report'), ('prescription', 'Prescription'), ('scan', 'Medical Scan'), ('blood_report', 'Blood Report'), ('general', 'General Record')], default='general', max_length=50)),
                ('date_of_record', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='ehr_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_record', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ehr_documents/')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_scanned', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ehr_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ehr.ehrrecord')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ehr_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehr.ehrrecord')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ehr_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentEHRLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_permission_granted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehr_links', to='appointments.appointment')),
                ('ehr_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_links', to='ehr.ehrrecord')),
            ],
            options={
                'unique_together': {('appointment', 'ehr_record')},
            },
        ),
    ]
